# Generated by Django 2.2.6 on 2019-10-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Singup',
            new_name='Signup',
        ),
    ]
